namespace xjustiz.core_dotnet.Models.Codes.Staat;

using System;
using System.Collections.Generic;

public static partial class StaatCodeMapper
{
    private static readonly Dictionary<string, StaatCode> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        { "000", StaatCode.Deutschland },
        { "121", StaatCode.Albanien },
        { "122", StaatCode.Bosnien_und_Herzegowina },
        { "123", StaatCode.Andorra },
        { "124", StaatCode.Belgien },
        { "125", StaatCode.Bulgarien },
        { "126", StaatCode.Daenemark },
        { "127", StaatCode.Estland },
        { "128", StaatCode.Finnland },
        { "129", StaatCode.Frankreich },
        { "130", StaatCode.Kroatien },
        { "131", StaatCode.Slowenien },
        { "134", StaatCode.Griechenland },
        { "135", StaatCode.Irland },
        { "136", StaatCode.Island },
        { "137", StaatCode.Italien },
        { "139", StaatCode.Lettland },
        { "140", StaatCode.Montenegro },
        { "141", StaatCode.Liechtenstein },
        { "142", StaatCode.Litauen },
        { "143", StaatCode.Luxemburg },
        { "144", StaatCode.Nordmazedonien },
        { "145", StaatCode.Malta },
        { "146", StaatCode.Republik_Moldau },
        { "147", StaatCode.Monaco },
        { "148", StaatCode.Koenigreich_der_Niederlande },
        { "149", StaatCode.Norwegen },
        { "150", StaatCode.Kosovo },
        { "151", StaatCode.Oesterreich },
        { "152", StaatCode.Polen },
        { "153", StaatCode.Portugal },
        { "154", StaatCode.Rumaenien },
        { "155", StaatCode.Slowakei },
        { "156", StaatCode.San_Marino },
        { "157", StaatCode.Schweden },
        { "158", StaatCode.Schweiz },
        { "160", StaatCode.Russische_Foederation },
        { "161", StaatCode.Spanien },
        { "163", StaatCode.Tuerkei },
        { "164", StaatCode.Tschechien },
        { "165", StaatCode.Ungarn },
        { "166", StaatCode.Ukraine },
        { "167", StaatCode.Vatikanstadt },
        { "168", StaatCode.Vereinigtes_Koenigreich },
        { "169", StaatCode.Belarus },
        { "170", StaatCode.Serbien },
        { "181", StaatCode.Zypern },
        { "221", StaatCode.Algerien },
        { "223", StaatCode.Angola },
        { "224", StaatCode.Eritrea },
        { "225", StaatCode.Aethiopien },
        { "226", StaatCode.Lesotho },
        { "227", StaatCode.Botsuana },
        { "229", StaatCode.Benin },
        { "230", StaatCode.Dschibuti },
        { "231", StaatCode.C_te_d_Ivoire },
        { "232", StaatCode.Nigeria },
        { "233", StaatCode.Simbabwe },
        { "236", StaatCode.Gabun },
        { "237", StaatCode.Gambia },
        { "238", StaatCode.Ghana },
        { "239", StaatCode.Mauretanien },
        { "242", StaatCode.Cabo_Verde },
        { "243", StaatCode.Kenia },
        { "244", StaatCode.Komoren },
        { "245", StaatCode.Kongo },
        { "246", StaatCode.Demokratische_Republik_Kongo },
        { "247", StaatCode.Liberia },
        { "248", StaatCode.Libyen },
        { "249", StaatCode.Madagaskar },
        { "251", StaatCode.Mali },
        { "252", StaatCode.Marokko },
        { "253", StaatCode.Mauritius },
        { "254", StaatCode.Mosambik },
        { "255", StaatCode.Niger },
        { "256", StaatCode.Malawi },
        { "257", StaatCode.Sambia },
        { "258", StaatCode.Burkina_Faso },
        { "259", StaatCode.Guinea_Bissau },
        { "261", StaatCode.Guinea },
        { "262", StaatCode.Kamerun },
        { "263", StaatCode.Suedafrika },
        { "265", StaatCode.Ruanda },
        { "267", StaatCode.Namibia },
        { "268", StaatCode.S_o_Tom_und_Pr_ncipe },
        { "269", StaatCode.Senegal },
        { "271", StaatCode.Seychellen },
        { "272", StaatCode.Sierra_Leone },
        { "273", StaatCode.Somalia },
        { "274", StaatCode.Aequatorialguinea },
        { "277", StaatCode.Sudan },
        { "278", StaatCode.Suedsudan },
        { "281", StaatCode.Eswatini },
        { "282", StaatCode.Vereinigte_Republik_Tansania },
        { "283", StaatCode.Togo },
        { "284", StaatCode.Tschad },
        { "285", StaatCode.Tunesien },
        { "286", StaatCode.Uganda },
        { "287", StaatCode.Aegypten },
        { "289", StaatCode.Zentralafrikanische_Republik },
        { "291", StaatCode.Burundi },
        { "320", StaatCode.Antigua_und_Barbuda },
        { "322", StaatCode.Barbados },
        { "323", StaatCode.Argentinien },
        { "324", StaatCode.Bahamas },
        { "326", StaatCode.Plurinationaler_Staat_Bolivien },
        { "327", StaatCode.Brasilien },
        { "328", StaatCode.Guyana },
        { "330", StaatCode.Belize },
        { "332", StaatCode.Chile },
        { "333", StaatCode.Dominica },
        { "334", StaatCode.Costa_Rica },
        { "335", StaatCode.Dominikanische_Republik },
        { "336", StaatCode.Ecuador },
        { "337", StaatCode.El_Salvador },
        { "340", StaatCode.Grenada },
        { "345", StaatCode.Guatemala },
        { "346", StaatCode.Haiti },
        { "347", StaatCode.Honduras },
        { "348", StaatCode.Kanada },
        { "349", StaatCode.Kolumbien },
        { "351", StaatCode.Kuba },
        { "353", StaatCode.Mexiko },
        { "354", StaatCode.Nicaragua },
        { "355", StaatCode.Jamaika },
        { "357", StaatCode.Panama },
        { "359", StaatCode.Paraguay },
        { "361", StaatCode.Peru },
        { "364", StaatCode.Suriname },
        { "365", StaatCode.Uruguay },
        { "366", StaatCode.St_Lucia },
        { "367", StaatCode.Bolivarische_Republik_Venezuela },
        { "368", StaatCode.Vereinigte_Staaten },
        { "369", StaatCode.St_Vincent_und_die_Grenadinen },
        { "370", StaatCode.St_Kitts_und_Nevis },
        { "371", StaatCode.Trinidad_und_Tobago },
        { "421", StaatCode.Jemen },
        { "422", StaatCode.Armenien },
        { "423", StaatCode.Afghanistan },
        { "424", StaatCode.Bahrain },
        { "425", StaatCode.Aserbaidschan },
        { "426", StaatCode.Bhutan },
        { "427", StaatCode.Myanmar },
        { "429", StaatCode.Brunei_Darussalam },
        { "430", StaatCode.Georgien },
        { "431", StaatCode.Sri_Lanka },
        { "432", StaatCode.Vietnam },
        { "434", StaatCode.Demokratische_Volksrepublik_Korea },
        { "436", StaatCode.Indien },
        { "437", StaatCode.Indonesien },
        { "438", StaatCode.Irak },
        { "439", StaatCode.Islamische_Republik_Iran },
        { "441", StaatCode.Israel },
        { "442", StaatCode.Japan },
        { "444", StaatCode.Kasachstan },
        { "445", StaatCode.Jordanien },
        { "446", StaatCode.Kambodscha },
        { "447", StaatCode.Katar },
        { "448", StaatCode.Kuwait },
        { "449", StaatCode.Demokratische_Volksrepublik_Laos },
        { "450", StaatCode.Kirgisistan },
        { "451", StaatCode.Libanon },
        { "454", StaatCode.Malediven },
        { "456", StaatCode.Oman },
        { "457", StaatCode.Mongolei },
        { "458", StaatCode.Nepal },
        { "460", StaatCode.Bangladesch },
        { "461", StaatCode.Pakistan },
        { "462", StaatCode.Philippinen },
        { "467", StaatCode.Republik_Korea },
        { "469", StaatCode.Vereinigte_Arabische_Emirate },
        { "470", StaatCode.Tadschikistan },
        { "471", StaatCode.Turkmenistan },
        { "472", StaatCode.Saudi_Arabien },
        { "474", StaatCode.Singapur },
        { "475", StaatCode.Arabische_Republik_Syrien },
        { "476", StaatCode.Thailand },
        { "477", StaatCode.Usbekistan },
        { "479", StaatCode.China },
        { "482", StaatCode.Malaysia },
        { "483", StaatCode.Timor_Leste },
        { "523", StaatCode.Australien },
        { "524", StaatCode.Salomonen },
        { "526", StaatCode.Fidschi },
        { "527", StaatCode.Cookinseln },
        { "530", StaatCode.Kiribati },
        { "531", StaatCode.Nauru },
        { "532", StaatCode.Vanuatu },
        { "533", StaatCode.Niue },
        { "536", StaatCode.Neuseeland },
        { "537", StaatCode.Palau },
        { "538", StaatCode.Papua_Neuguinea },
        { "540", StaatCode.Tuvalu },
        { "541", StaatCode.Tonga },
        { "543", StaatCode.Samoa },
        { "544", StaatCode.Marshallinseln },
        { "545", StaatCode.Foederierte_Staaten_von_Mikronesien },
        { "AD", StaatCode.Andorra },
        { "AE", StaatCode.Vereinigte_Arabische_Emirate },
        { "AF", StaatCode.Afghanistan },
        { "AFG", StaatCode.Afghanistan },
        { "afghanisch", StaatCode.Afghanistan },
        { "Afghanistan", StaatCode.Afghanistan },
        { "AG", StaatCode.Antigua_und_Barbuda },
        { "AGO", StaatCode.Angola },
        { "Ägypten", StaatCode.Aegypten },
        { "ägyptisch", StaatCode.Aegypten },
        { "AL", StaatCode.Albanien },
        { "ALB", StaatCode.Albanien },
        { "Albanien", StaatCode.Albanien },
        { "albanisch", StaatCode.Albanien },
        { "Algerien", StaatCode.Algerien },
        { "algerisch", StaatCode.Algerien },
        { "AM", StaatCode.Armenien },
        { "amerikanisch", StaatCode.Vereinigte_Staaten },
        { "AND", StaatCode.Andorra },
        { "Andorra", StaatCode.Andorra },
        { "andorranisch", StaatCode.Andorra },
        { "Angola", StaatCode.Angola },
        { "angolanisch", StaatCode.Angola },
        { "Antigua und Barbuda", StaatCode.Antigua_und_Barbuda },
        { "antiguanisch", StaatCode.Antigua_und_Barbuda },
        { "AO", StaatCode.Angola },
        { "Äquatorialguinea", StaatCode.Aequatorialguinea },
        { "äquatorialguineisch", StaatCode.Aequatorialguinea },
        { "AR", StaatCode.Argentinien },
        { "Arabische Republik Syrien", StaatCode.Arabische_Republik_Syrien },
        { "ARE", StaatCode.Vereinigte_Arabische_Emirate },
        { "ARG", StaatCode.Argentinien },
        { "Argentinien", StaatCode.Argentinien },
        { "argentinisch", StaatCode.Argentinien },
        { "ARM", StaatCode.Armenien },
        { "Armenien", StaatCode.Armenien },
        { "armenisch", StaatCode.Armenien },
        { "Aserbaidschan", StaatCode.Aserbaidschan },
        { "aserbaidschanisch", StaatCode.Aserbaidschan },
        { "AT", StaatCode.Oesterreich },
        { "ATG", StaatCode.Antigua_und_Barbuda },
        { "Äthiopien", StaatCode.Aethiopien },
        { "äthiopisch", StaatCode.Aethiopien },
        { "AU", StaatCode.Australien },
        { "AUS", StaatCode.Australien },
        { "Australien", StaatCode.Australien },
        { "australisch", StaatCode.Australien },
        { "AUT", StaatCode.Oesterreich },
        { "AZ", StaatCode.Aserbaidschan },
        { "AZE", StaatCode.Aserbaidschan },
        { "BA", StaatCode.Bosnien_und_Herzegowina },
        { "bahamaisch", StaatCode.Bahamas },
        { "Bahamas", StaatCode.Bahamas },
        { "Bahrain", StaatCode.Bahrain },
        { "bahrainisch", StaatCode.Bahrain },
        { "Bangladesch", StaatCode.Bangladesch },
        { "bangladeschisch", StaatCode.Bangladesch },
        { "barbadisch", StaatCode.Barbados },
        { "Barbados", StaatCode.Barbados },
        { "BB", StaatCode.Barbados },
        { "BD", StaatCode.Bangladesch },
        { "BDI", StaatCode.Burundi },
        { "BE", StaatCode.Belgien },
        { "BEL", StaatCode.Belgien },
        { "Belarus", StaatCode.Belarus },
        { "belarussisch", StaatCode.Belarus },
        { "Belgien", StaatCode.Belgien },
        { "belgisch", StaatCode.Belgien },
        { "Belize", StaatCode.Belize },
        { "belizisch", StaatCode.Belize },
        { "BEN", StaatCode.Benin },
        { "Benin", StaatCode.Benin },
        { "beninisch", StaatCode.Benin },
        { "BF", StaatCode.Burkina_Faso },
        { "BFA", StaatCode.Burkina_Faso },
        { "BG", StaatCode.Bulgarien },
        { "BGD", StaatCode.Bangladesch },
        { "BGR", StaatCode.Bulgarien },
        { "BH", StaatCode.Bahrain },
        { "BHR", StaatCode.Bahrain },
        { "BHS", StaatCode.Bahamas },
        { "Bhutan", StaatCode.Bhutan },
        { "bhutanisch", StaatCode.Bhutan },
        { "BI", StaatCode.Burundi },
        { "BIH", StaatCode.Bosnien_und_Herzegowina },
        { "BJ", StaatCode.Benin },
        { "BLR", StaatCode.Belarus },
        { "BLZ", StaatCode.Belize },
        { "BN", StaatCode.Brunei_Darussalam },
        { "BO", StaatCode.Plurinationaler_Staat_Bolivien },
        { "BOL", StaatCode.Plurinationaler_Staat_Bolivien },
        { "Bolivarische Republik Venezuela", StaatCode.Bolivarische_Republik_Venezuela },
        { "bolivianisch", StaatCode.Plurinationaler_Staat_Bolivien },
        { "Bolivien", StaatCode.Plurinationaler_Staat_Bolivien },
        { "Bosnien und Herzegowina", StaatCode.Bosnien_und_Herzegowina },
        { "bosnisch-herzegowinisch", StaatCode.Bosnien_und_Herzegowina },
        { "Botsuana", StaatCode.Botsuana },
        { "botsuanisch", StaatCode.Botsuana },
        { "BR", StaatCode.Brasilien },
        { "BRA", StaatCode.Brasilien },
        { "brasilianisch", StaatCode.Brasilien },
        { "Brasilien", StaatCode.Brasilien },
        { "BRB", StaatCode.Barbados },
        { "britisch", StaatCode.Vereinigtes_Koenigreich },
        { "BRN", StaatCode.Brunei_Darussalam },
        { "Brunei Darussalam", StaatCode.Brunei_Darussalam },
        { "bruneiisch", StaatCode.Brunei_Darussalam },
        { "BS", StaatCode.Bahamas },
        { "BT", StaatCode.Bhutan },
        { "BTN", StaatCode.Bhutan },
        { "Bulgarien", StaatCode.Bulgarien },
        { "bulgarisch", StaatCode.Bulgarien },
        { "Burkina Faso", StaatCode.Burkina_Faso },
        { "burkinisch", StaatCode.Burkina_Faso },
        { "Burundi", StaatCode.Burundi },
        { "burundisch", StaatCode.Burundi },
        { "BW", StaatCode.Botsuana },
        { "BWA", StaatCode.Botsuana },
        { "BY", StaatCode.Belarus },
        { "BZ", StaatCode.Belize },
        { "CA", StaatCode.Kanada },
        { "Cabo Verde", StaatCode.Cabo_Verde },
        { "cabo-verdisch", StaatCode.Cabo_Verde },
        { "CAF", StaatCode.Zentralafrikanische_Republik },
        { "CAN", StaatCode.Kanada },
        { "CD", StaatCode.Demokratische_Republik_Kongo },
        { "CF", StaatCode.Zentralafrikanische_Republik },
        { "CG", StaatCode.Kongo },
        { "CH", StaatCode.Schweiz },
        { "CHE", StaatCode.Schweiz },
        { "Chile", StaatCode.Chile },
        { "chilenisch", StaatCode.Chile },
        { "China", StaatCode.China },
        { "chinesisch", StaatCode.China },
        { "CHL", StaatCode.Chile },
        { "CHN", StaatCode.China },
        { "CI", StaatCode.C_te_d_Ivoire },
        { "CIV", StaatCode.C_te_d_Ivoire },
        { "CK", StaatCode.Cookinseln },
        { "CL", StaatCode.Chile },
        { "CM", StaatCode.Kamerun },
        { "CMR", StaatCode.Kamerun },
        { "CN", StaatCode.China },
        { "CO", StaatCode.Kolumbien },
        { "COD", StaatCode.Demokratische_Republik_Kongo },
        { "COG", StaatCode.Kongo },
        { "COK", StaatCode.Cookinseln },
        { "COL", StaatCode.Kolumbien },
        { "COM", StaatCode.Komoren },
        { "Cookinseln", StaatCode.Cookinseln },
        { "Costa Rica", StaatCode.Costa_Rica },
        { "costa-ricanisch", StaatCode.Costa_Rica },
        { "Côte d’Ivoire", StaatCode.C_te_d_Ivoire },
        { "CPV", StaatCode.Cabo_Verde },
        { "CR", StaatCode.Costa_Rica },
        { "CRI", StaatCode.Costa_Rica },
        { "CU", StaatCode.Kuba },
        { "CUB", StaatCode.Kuba },
        { "CV", StaatCode.Cabo_Verde },
        { "CY", StaatCode.Zypern },
        { "CYP", StaatCode.Zypern },
        { "CZ", StaatCode.Tschechien },
        { "CZE", StaatCode.Tschechien },
        { "Dänemark", StaatCode.Daenemark },
        { "dänisch", StaatCode.Daenemark },
        { "das Commonwealth der Bahamas", StaatCode.Bahamas },
        { "das Commonwealth Dominica", StaatCode.Dominica },
        { "das Fürstentum Andorra", StaatCode.Andorra },
        { "das Fürstentum Liechtenstein", StaatCode.Liechtenstein },
        { "das Fürstentum Monaco", StaatCode.Monaco },
        { "das Großherzogtum Luxemburg", StaatCode.Luxemburg },
        { "das Haschemitische Königreich Jordanien", StaatCode.Jordanien },
        { "das Königreich Bahrain", StaatCode.Bahrain },
        { "das Königreich Belgien", StaatCode.Belgien },
        { "das Königreich Bhutan", StaatCode.Bhutan },
        { "das Königreich Dänemark", StaatCode.Daenemark },
        { "das Königreich der Niederlande", StaatCode.Koenigreich_der_Niederlande },
        { "das Königreich Eswatini", StaatCode.Eswatini },
        { "das Königreich Kambodscha", StaatCode.Kambodscha },
        { "das Königreich Lesotho", StaatCode.Lesotho },
        { "das Königreich Marokko", StaatCode.Marokko },
        { "das Königreich Norwegen", StaatCode.Norwegen },
        { "das Königreich Saudi-Arabien", StaatCode.Saudi_Arabien },
        { "das Königreich Schweden", StaatCode.Schweden },
        { "das Königreich Spanien", StaatCode.Spanien },
        { "das Königreich Thailand", StaatCode.Thailand },
        { "das Königreich Tonga", StaatCode.Tonga },
        { "das Sultanat Oman", StaatCode.Oman },
        { "das Vereinigte Königreich Großbritannien und Nordirland", StaatCode.Vereinigtes_Koenigreich },
        { "DE", StaatCode.Deutschland },
        { "Demokratische Republik Kongo", StaatCode.Demokratische_Republik_Kongo },
        { "Demokratische Volksrepublik Korea", StaatCode.Demokratische_Volksrepublik_Korea },
        { "Demokratische Volksrepublik Laos", StaatCode.Demokratische_Volksrepublik_Laos },
        { "der Demokratischen Republik Kongo", StaatCode.Demokratische_Republik_Kongo },
        { "der Demokratischen Volksrepublik Korea", StaatCode.Demokratische_Volksrepublik_Korea },
        { "der Plurinationale Staat Bolivien", StaatCode.Plurinationaler_Staat_Bolivien },
        { "der Republik Korea", StaatCode.Republik_Korea },
        { "der Staat Eritrea", StaatCode.Eritrea },
        { "der Staat Israel", StaatCode.Israel },
        { "der Staat Katar", StaatCode.Katar },
        { "der Staat Kuwait", StaatCode.Kuwait },
        { "der Staat Libyen", StaatCode.Libyen },
        { "der Staat Vatikanstadt", StaatCode.Vatikanstadt },
        { "der Unabhängige Staat Papua-Neuguinea", StaatCode.Papua_Neuguinea },
        { "der Unabhängige Staat Samoa", StaatCode.Samoa },
        { "der Vereinigten Arabischen Emirate", StaatCode.Vereinigte_Arabische_Emirate },
        { "DEU", StaatCode.Deutschland },
        { "deutsch", StaatCode.Deutschland },
        { "Deutschland", StaatCode.Deutschland },
        { "die Arabische Republik Ägypten", StaatCode.Aegypten },
        { "die Arabische Republik Syrien", StaatCode.Arabische_Republik_Syrien },
        { "die Argentinische Republik", StaatCode.Argentinien },
        { "die Bolivarische Republik Venezuela", StaatCode.Bolivarische_Republik_Venezuela },
        { "die Bundesrepublik Deutschland", StaatCode.Deutschland },
        { "die Bundesrepublik Nigeria", StaatCode.Nigeria },
        { "die Bundesrepublik Somalia", StaatCode.Somalia },
        { "die Cookinseln", StaatCode.Cookinseln },
        { "die Demokratische Bundesrepublik Äthiopien", StaatCode.Aethiopien },
        { "die Demokratische Republik Kongo", StaatCode.Demokratische_Republik_Kongo },
        { "die Demokratische Republik São Tomé und Príncipe", StaatCode.S_o_Tom_und_Pr_ncipe },
        { "die Demokratische Republik Timor-Leste", StaatCode.Timor_Leste },
        { "die Demokratische Sozialistische Republik Sri Lanka", StaatCode.Sri_Lanka },
        { "die Demokratische Volksrepublik Algerien", StaatCode.Algerien },
        { "die Demokratische Volksrepublik Korea", StaatCode.Demokratische_Volksrepublik_Korea },
        { "die Demokratische Volksrepublik Laos", StaatCode.Demokratische_Volksrepublik_Laos },
        { "die Dominikanische Republik", StaatCode.Dominikanische_Republik },
        { "die Föderation St. Kitts und Nevis", StaatCode.St_Kitts_und_Nevis },
        { "die Föderative Republik Brasilien", StaatCode.Brasilien },
        { "die Föderierten Staaten von Mikronesien", StaatCode.Foederierte_Staaten_von_Mikronesien },
        { "die Französische Republik", StaatCode.Frankreich },
        { "die Gabunische Republik", StaatCode.Gabun },
        { "die Hellenische Republik", StaatCode.Griechenland },
        { "die Islamische Republik Afghanistan", StaatCode.Afghanistan },
        { "die Islamische Republik Iran", StaatCode.Islamische_Republik_Iran },
        { "die Islamische Republik Mauretanien", StaatCode.Mauretanien },
        { "die Islamische Republik Pakistan", StaatCode.Pakistan },
        { "die Italienische Republik", StaatCode.Italien },
        { "die Kirgisische Republik", StaatCode.Kirgisistan },
        { "die Kooperative Republik Guyana", StaatCode.Guyana },
        { "die Libanesische Republik", StaatCode.Libanon },
        { "die Mongolei", StaatCode.Mongolei },
        { "die Portugiesische Republik", StaatCode.Portugal },
        { "die Republik Albanien", StaatCode.Albanien },
        { "die Republik Angola", StaatCode.Angola },
        { "die Republik Äquatorialguinea", StaatCode.Aequatorialguinea },
        { "die Republik Armenien", StaatCode.Armenien },
        { "die Republik Aserbaidschan", StaatCode.Aserbaidschan },
        { "die Republik Belarus", StaatCode.Belarus },
        { "die Republik Benin", StaatCode.Benin },
        { "die Republik Botsuana", StaatCode.Botsuana },
        { "die Republik Bulgarien", StaatCode.Bulgarien },
        { "die Republik Burundi", StaatCode.Burundi },
        { "die Republik Cabo Verde", StaatCode.Cabo_Verde },
        { "die Republik Chile", StaatCode.Chile },
        { "die Republik Costa Rica", StaatCode.Costa_Rica },
        { "die Republik Côte d’Ivoire", StaatCode.C_te_d_Ivoire },
        { "die Republik der Philippinen", StaatCode.Philippinen },
        { "die Republik der Union Myanmar", StaatCode.Myanmar },
        { "die Republik Dschibuti", StaatCode.Dschibuti },
        { "die Republik Ecuador", StaatCode.Ecuador },
        { "die Republik El Salvador", StaatCode.El_Salvador },
        { "die Republik Estland", StaatCode.Estland },
        { "die Republik Fidschi", StaatCode.Fidschi },
        { "die Republik Finnland", StaatCode.Finnland },
        { "die Republik Gambia", StaatCode.Gambia },
        { "die Republik Ghana", StaatCode.Ghana },
        { "die Republik Guatemala", StaatCode.Guatemala },
        { "die Republik Guinea", StaatCode.Guinea },
        { "die Republik Guinea-Bissau", StaatCode.Guinea_Bissau },
        { "die Republik Haiti", StaatCode.Haiti },
        { "die Republik Honduras", StaatCode.Honduras },
        { "die Republik Indien", StaatCode.Indien },
        { "die Republik Indonesien", StaatCode.Indonesien },
        { "die Republik Irak", StaatCode.Irak },
        { "die Republik Jemen", StaatCode.Jemen },
        { "die Republik Kamerun", StaatCode.Kamerun },
        { "die Republik Kasachstan", StaatCode.Kasachstan },
        { "die Republik Kenia", StaatCode.Kenia },
        { "die Republik Kiribati", StaatCode.Kiribati },
        { "die Republik Kolumbien", StaatCode.Kolumbien },
        { "die Republik Kongo", StaatCode.Kongo },
        { "die Republik Korea", StaatCode.Republik_Korea },
        { "die Republik Kosovo", StaatCode.Kosovo },
        { "die Republik Kroatien", StaatCode.Kroatien },
        { "die Republik Kuba", StaatCode.Kuba },
        { "die Republik Lettland", StaatCode.Lettland },
        { "die Republik Liberia", StaatCode.Liberia },
        { "die Republik Litauen", StaatCode.Litauen },
        { "die Republik Madagaskar", StaatCode.Madagaskar },
        { "die Republik Malawi", StaatCode.Malawi },
        { "die Republik Malediven", StaatCode.Malediven },
        { "die Republik Mali", StaatCode.Mali },
        { "die Republik Malta", StaatCode.Malta },
        { "die Republik Marshallinseln", StaatCode.Marshallinseln },
        { "die Republik Mauritius", StaatCode.Mauritius },
        { "die Republik Moldau", StaatCode.Republik_Moldau },
        { "die Republik Mosambik", StaatCode.Mosambik },
        { "die Republik Namibia", StaatCode.Namibia },
        { "die Republik Nauru", StaatCode.Nauru },
        { "die Republik Nicaragua", StaatCode.Nicaragua },
        { "die Republik Niger", StaatCode.Niger },
        { "die Republik Nordmazedonien", StaatCode.Nordmazedonien },
        { "die Republik Österreich", StaatCode.Oesterreich },
        { "die Republik Östlich des Uruguay", StaatCode.Uruguay },
        { "die Republik Palau", StaatCode.Palau },
        { "die Republik Panama", StaatCode.Panama },
        { "die Republik Paraguay", StaatCode.Paraguay },
        { "die Republik Peru", StaatCode.Peru },
        { "die Republik Polen", StaatCode.Polen },
        { "die Republik Ruanda", StaatCode.Ruanda },
        { "die Republik Sambia", StaatCode.Sambia },
        { "die Republik San Marino", StaatCode.San_Marino },
        { "die Republik Senegal", StaatCode.Senegal },
        { "die Republik Serbien", StaatCode.Serbien },
        { "die Republik Seychellen", StaatCode.Seychellen },
        { "die Republik Sierra Leone", StaatCode.Sierra_Leone },
        { "die Republik Simbabwe", StaatCode.Simbabwe },
        { "die Republik Singapur", StaatCode.Singapur },
        { "die Republik Slowenien", StaatCode.Slowenien },
        { "die Republik Südafrika", StaatCode.Suedafrika },
        { "die Republik Sudan", StaatCode.Sudan },
        { "die Republik Südsudan", StaatCode.Suedsudan },
        { "die Republik Suriname", StaatCode.Suriname },
        { "die Republik Tadschikistan", StaatCode.Tadschikistan },
        { "die Republik Togo", StaatCode.Togo },
        { "die Republik Trinidad und Tobago", StaatCode.Trinidad_und_Tobago },
        { "die Republik Tschad", StaatCode.Tschad },
        { "die Republik Türkei", StaatCode.Tuerkei },
        { "die Republik Uganda", StaatCode.Uganda },
        { "die Republik Usbekistan", StaatCode.Usbekistan },
        { "die Republik Vanuatu", StaatCode.Vanuatu },
        { "die Republik Zypern", StaatCode.Zypern },
        { "die Russische Föderation", StaatCode.Russische_Foederation },
        { "die Salomonen", StaatCode.Salomonen },
        { "die Schweizerische Eidgenossenschaft", StaatCode.Schweiz },
        { "die Slowakische Republik", StaatCode.Slowakei },
        { "die Sozialistische Republik Vietnam", StaatCode.Vietnam },
        { "die Tschechische Republik", StaatCode.Tschechien },
        { "die Tunesische Republik", StaatCode.Tunesien },
        { "die Ukraine", StaatCode.Ukraine },
        { "die Union der Komoren", StaatCode.Komoren },
        { "die Vereinigte Republik Tansania", StaatCode.Vereinigte_Republik_Tansania },
        { "die Vereinigten Arabischen Emirate (Abu Dhabi, Adschman, Dubai, Fudschaira, Ras al Chaima, Schardscha, Umm al Kaiwain)", StaatCode.Vereinigte_Arabische_Emirate },
        { "die Vereinigten Mexikanischen Staaten", StaatCode.Mexiko },
        { "die Vereinigten Staaten von Amerika", StaatCode.Vereinigte_Staaten },
        { "die Volksrepublik Bangladesch", StaatCode.Bangladesch },
        { "die Volksrepublik China", StaatCode.China },
        { "die Zentralafrikanische Republik", StaatCode.Zentralafrikanische_Republik },
        { "DJ", StaatCode.Dschibuti },
        { "DJI", StaatCode.Dschibuti },
        { "DK", StaatCode.Daenemark },
        { "DM", StaatCode.Dominica },
        { "DMA", StaatCode.Dominica },
        { "DNK", StaatCode.Daenemark },
        { "DO", StaatCode.Dominikanische_Republik },
        { "DOM", StaatCode.Dominikanische_Republik },
        { "Dominica", StaatCode.Dominica },
        { "dominicanisch", StaatCode.Dominica },
        { "dominikanisch", StaatCode.Dominikanische_Republik },
        { "Dominikanische Republik", StaatCode.Dominikanische_Republik },
        { "Dschibuti", StaatCode.Dschibuti },
        { "dschibutisch", StaatCode.Dschibuti },
        { "DZ", StaatCode.Algerien },
        { "DZA", StaatCode.Algerien },
        { "EC", StaatCode.Ecuador },
        { "ECU", StaatCode.Ecuador },
        { "Ecuador", StaatCode.Ecuador },
        { "ecuadorianisch", StaatCode.Ecuador },
        { "EE", StaatCode.Estland },
        { "EG", StaatCode.Aegypten },
        { "EGY", StaatCode.Aegypten },
        { "El Salvador", StaatCode.El_Salvador },
        { "ER", StaatCode.Eritrea },
        { "ERI", StaatCode.Eritrea },
        { "Eritrea", StaatCode.Eritrea },
        { "eritreisch", StaatCode.Eritrea },
        { "ES", StaatCode.Spanien },
        { "ESP", StaatCode.Spanien },
        { "EST", StaatCode.Estland },
        { "Estland", StaatCode.Estland },
        { "estnisch", StaatCode.Estland },
        { "Eswatini", StaatCode.Eswatini },
        { "eswatinisch", StaatCode.Eswatini },
        { "ET", StaatCode.Aethiopien },
        { "ETH", StaatCode.Aethiopien },
        { "FI", StaatCode.Finnland },
        { "Fidschi", StaatCode.Fidschi },
        { "fidschianisch", StaatCode.Fidschi },
        { "FIN", StaatCode.Finnland },
        { "finnisch", StaatCode.Finnland },
        { "Finnland", StaatCode.Finnland },
        { "FJ", StaatCode.Fidschi },
        { "FJI", StaatCode.Fidschi },
        { "FM", StaatCode.Foederierte_Staaten_von_Mikronesien },
        { "Föderierte Staaten von Mikronesien", StaatCode.Foederierte_Staaten_von_Mikronesien },
        { "FR", StaatCode.Frankreich },
        { "FRA", StaatCode.Frankreich },
        { "Frankreich", StaatCode.Frankreich },
        { "französisch", StaatCode.Frankreich },
        { "FSM", StaatCode.Foederierte_Staaten_von_Mikronesien },
        { "GA", StaatCode.Gabun },
        { "GAB", StaatCode.Gabun },
        { "Gabun", StaatCode.Gabun },
        { "gabunisch", StaatCode.Gabun },
        { "Gambia", StaatCode.Gambia },
        { "gambisch", StaatCode.Gambia },
        { "GB", StaatCode.Vereinigtes_Koenigreich },
        { "GBR", StaatCode.Vereinigtes_Koenigreich },
        { "GD", StaatCode.Grenada },
        { "GE", StaatCode.Georgien },
        { "GEO", StaatCode.Georgien },
        { "Georgien", StaatCode.Georgien },
        { "georgisch", StaatCode.Georgien },
        { "GH", StaatCode.Ghana },
        { "GHA", StaatCode.Ghana },
        { "Ghana", StaatCode.Ghana },
        { "ghanaisch", StaatCode.Ghana },
        { "GIN", StaatCode.Guinea },
        { "GM", StaatCode.Gambia },
        { "GMB", StaatCode.Gambia },
        { "GN", StaatCode.Guinea },
        { "GNB", StaatCode.Guinea_Bissau },
        { "GNQ", StaatCode.Aequatorialguinea },
        { "GQ", StaatCode.Aequatorialguinea },
        { "GR", StaatCode.Griechenland },
        { "GRC", StaatCode.Griechenland },
        { "GRD", StaatCode.Grenada },
        { "Grenada", StaatCode.Grenada },
        { "grenadisch", StaatCode.Grenada },
        { "Griechenland", StaatCode.Griechenland },
        { "griechisch", StaatCode.Griechenland },
        { "GT", StaatCode.Guatemala },
        { "GTM", StaatCode.Guatemala },
        { "Guatemala", StaatCode.Guatemala },
        { "guatemaltekisch", StaatCode.Guatemala },
        { "Guinea", StaatCode.Guinea },
        { "Guinea-Bissau", StaatCode.Guinea_Bissau },
        { "guinea-bissauisch", StaatCode.Guinea_Bissau },
        { "guineisch", StaatCode.Guinea },
        { "GUY", StaatCode.Guyana },
        { "Guyana", StaatCode.Guyana },
        { "guyanisch", StaatCode.Guyana },
        { "GW", StaatCode.Guinea_Bissau },
        { "GY", StaatCode.Guyana },
        { "Haiti", StaatCode.Haiti },
        { "haitianisch", StaatCode.Haiti },
        { "HN", StaatCode.Honduras },
        { "HND", StaatCode.Honduras },
        { "honduranisch", StaatCode.Honduras },
        { "Honduras", StaatCode.Honduras },
        { "HR", StaatCode.Kroatien },
        { "HRV", StaatCode.Kroatien },
        { "HT", StaatCode.Haiti },
        { "HTI", StaatCode.Haiti },
        { "HU", StaatCode.Ungarn },
        { "HUN", StaatCode.Ungarn },
        { "ID", StaatCode.Indonesien },
        { "IDN", StaatCode.Indonesien },
        { "IE", StaatCode.Irland },
        { "IL", StaatCode.Israel },
        { "IN", StaatCode.Indien },
        { "IND", StaatCode.Indien },
        { "Indien", StaatCode.Indien },
        { "indisch", StaatCode.Indien },
        { "Indonesien", StaatCode.Indonesien },
        { "indonesisch", StaatCode.Indonesien },
        { "IQ", StaatCode.Irak },
        { "IR", StaatCode.Islamische_Republik_Iran },
        { "Irak", StaatCode.Irak },
        { "irakisch", StaatCode.Irak },
        { "Iran", StaatCode.Islamische_Republik_Iran },
        { "iranisch", StaatCode.Islamische_Republik_Iran },
        { "irisch", StaatCode.Irland },
        { "IRL", StaatCode.Irland },
        { "Irland", StaatCode.Irland },
        { "IRN", StaatCode.Islamische_Republik_Iran },
        { "IRQ", StaatCode.Irak },
        { "IS", StaatCode.Island },
        { "ISL", StaatCode.Island },
        { "Islamische Republik Iran", StaatCode.Islamische_Republik_Iran },
        { "Island", StaatCode.Island },
        { "isländisch", StaatCode.Island },
        { "ISR", StaatCode.Israel },
        { "Israel", StaatCode.Israel },
        { "israelisch", StaatCode.Israel },
        { "IT", StaatCode.Italien },
        { "ITA", StaatCode.Italien },
        { "Italien", StaatCode.Italien },
        { "italienisch", StaatCode.Italien },
        { "ivorisch", StaatCode.C_te_d_Ivoire },
        { "JAM", StaatCode.Jamaika },
        { "Jamaika", StaatCode.Jamaika },
        { "jamaikanisch", StaatCode.Jamaika },
        { "Japan", StaatCode.Japan },
        { "japanisch", StaatCode.Japan },
        { "Jemen", StaatCode.Jemen },
        { "jemenitisch", StaatCode.Jemen },
        { "JM", StaatCode.Jamaika },
        { "JO", StaatCode.Jordanien },
        { "JOR", StaatCode.Jordanien },
        { "Jordanien", StaatCode.Jordanien },
        { "jordanisch", StaatCode.Jordanien },
        { "JP", StaatCode.Japan },
        { "JPN", StaatCode.Japan },
        { "Kambodscha", StaatCode.Kambodscha },
        { "kambodschanisch", StaatCode.Kambodscha },
        { "Kamerun", StaatCode.Kamerun },
        { "kamerunisch", StaatCode.Kamerun },
        { "Kanada", StaatCode.Kanada },
        { "kanadisch", StaatCode.Kanada },
        { "kasachisch", StaatCode.Kasachstan },
        { "Kasachstan", StaatCode.Kasachstan },
        { "Katar", StaatCode.Katar },
        { "katarisch", StaatCode.Katar },
        { "KAZ", StaatCode.Kasachstan },
        { "KE", StaatCode.Kenia },
        { "KEN", StaatCode.Kenia },
        { "Kenia", StaatCode.Kenia },
        { "kenianisch", StaatCode.Kenia },
        { "KG", StaatCode.Kirgisistan },
        { "KGZ", StaatCode.Kirgisistan },
        { "KH", StaatCode.Kambodscha },
        { "KHM", StaatCode.Kambodscha },
        { "KI", StaatCode.Kiribati },
        { "KIR", StaatCode.Kiribati },
        { "kirgisisch", StaatCode.Kirgisistan },
        { "Kirgisistan", StaatCode.Kirgisistan },
        { "Kiribati", StaatCode.Kiribati },
        { "kiribatisch", StaatCode.Kiribati },
        { "KM", StaatCode.Komoren },
        { "KN", StaatCode.St_Kitts_und_Nevis },
        { "KNA", StaatCode.St_Kitts_und_Nevis },
        { "kolumbianisch", StaatCode.Kolumbien },
        { "Kolumbien", StaatCode.Kolumbien },
        { "Komoren", StaatCode.Komoren },
        { "komorisch", StaatCode.Komoren },
        { "Kongo", StaatCode.Kongo },
        { "Kongo, Demokratische Republik", StaatCode.Demokratische_Republik_Kongo },
        { "kongolesisch", StaatCode.Kongo },
        { "Königreich der Niederlande", StaatCode.Koenigreich_der_Niederlande },
        { "KOR", StaatCode.Republik_Korea },
        { "Korea, Demokratische Volksrepublik", StaatCode.Demokratische_Volksrepublik_Korea },
        { "Korea, Republik", StaatCode.Republik_Korea },
        { "kosovarisch", StaatCode.Kosovo },
        { "Kosovo", StaatCode.Kosovo },
        { "KP", StaatCode.Demokratische_Volksrepublik_Korea },
        { "KR", StaatCode.Republik_Korea },
        { "Kroatien", StaatCode.Kroatien },
        { "kroatisch", StaatCode.Kroatien },
        { "Kuba", StaatCode.Kuba },
        { "kubanisch", StaatCode.Kuba },
        { "Kuwait", StaatCode.Kuwait },
        { "kuwaitisch", StaatCode.Kuwait },
        { "KW", StaatCode.Kuwait },
        { "KWT", StaatCode.Kuwait },
        { "KZ", StaatCode.Kasachstan },
        { "LA", StaatCode.Demokratische_Volksrepublik_Laos },
        { "LAO", StaatCode.Demokratische_Volksrepublik_Laos },
        { "Laos", StaatCode.Demokratische_Volksrepublik_Laos },
        { "laotisch", StaatCode.Demokratische_Volksrepublik_Laos },
        { "LB", StaatCode.Libanon },
        { "LBN", StaatCode.Libanon },
        { "LBR", StaatCode.Liberia },
        { "LBY", StaatCode.Libyen },
        { "LC", StaatCode.St_Lucia },
        { "LCA", StaatCode.St_Lucia },
        { "lesothisch", StaatCode.Lesotho },
        { "Lesotho", StaatCode.Lesotho },
        { "lettisch", StaatCode.Lettland },
        { "Lettland", StaatCode.Lettland },
        { "LI", StaatCode.Liechtenstein },
        { "libanesisch", StaatCode.Libanon },
        { "Libanon", StaatCode.Libanon },
        { "Liberia", StaatCode.Liberia },
        { "liberianisch", StaatCode.Liberia },
        { "Libyen", StaatCode.Libyen },
        { "libysch", StaatCode.Libyen },
        { "LIE", StaatCode.Liechtenstein },
        { "Liechtenstein", StaatCode.Liechtenstein },
        { "liechtensteinisch", StaatCode.Liechtenstein },
        { "Litauen", StaatCode.Litauen },
        { "litauisch", StaatCode.Litauen },
        { "LK", StaatCode.Sri_Lanka },
        { "LKA", StaatCode.Sri_Lanka },
        { "LR", StaatCode.Liberia },
        { "LS", StaatCode.Lesotho },
        { "LSO", StaatCode.Lesotho },
        { "LT", StaatCode.Litauen },
        { "LTU", StaatCode.Litauen },
        { "LU", StaatCode.Luxemburg },
        { "lucianisch", StaatCode.St_Lucia },
        { "LUX", StaatCode.Luxemburg },
        { "Luxemburg", StaatCode.Luxemburg },
        { "luxemburgisch", StaatCode.Luxemburg },
        { "LV", StaatCode.Lettland },
        { "LVA", StaatCode.Lettland },
        { "LY", StaatCode.Libyen },
        { "MA", StaatCode.Marokko },
        { "Madagaskar", StaatCode.Madagaskar },
        { "madagassisch", StaatCode.Madagaskar },
        { "Malawi", StaatCode.Malawi },
        { "malawisch", StaatCode.Malawi },
        { "Malaysia", StaatCode.Malaysia },
        { "malaysisch", StaatCode.Malaysia },
        { "Malediven", StaatCode.Malediven },
        { "maledivisch", StaatCode.Malediven },
        { "Mali", StaatCode.Mali },
        { "malisch", StaatCode.Mali },
        { "Malta", StaatCode.Malta },
        { "maltesisch", StaatCode.Malta },
        { "MAR", StaatCode.Marokko },
        { "marokkanisch", StaatCode.Marokko },
        { "Marokko", StaatCode.Marokko },
        { "Marshallinseln", StaatCode.Marshallinseln },
        { "marshallisch", StaatCode.Marshallinseln },
        { "Mauretanien", StaatCode.Mauretanien },
        { "mauretanisch", StaatCode.Mauretanien },
        { "mauritisch", StaatCode.Mauritius },
        { "Mauritius", StaatCode.Mauritius },
        { "mazedonisch/Bürger der Republik Nordmazedonien", StaatCode.Nordmazedonien },
        { "MC", StaatCode.Monaco },
        { "MCO", StaatCode.Monaco },
        { "MD", StaatCode.Republik_Moldau },
        { "MDA", StaatCode.Republik_Moldau },
        { "MDG", StaatCode.Madagaskar },
        { "MDV", StaatCode.Malediven },
        { "ME", StaatCode.Montenegro },
        { "MEX", StaatCode.Mexiko },
        { "mexikanisch", StaatCode.Mexiko },
        { "Mexiko", StaatCode.Mexiko },
        { "MG", StaatCode.Madagaskar },
        { "MH", StaatCode.Marshallinseln },
        { "MHL", StaatCode.Marshallinseln },
        { "Mikronesien", StaatCode.Foederierte_Staaten_von_Mikronesien },
        { "mikronesisch", StaatCode.Foederierte_Staaten_von_Mikronesien },
        { "MK", StaatCode.Nordmazedonien },
        { "MKD", StaatCode.Nordmazedonien },
        { "ML", StaatCode.Mali },
        { "MLI", StaatCode.Mali },
        { "MLT", StaatCode.Malta },
        { "MM", StaatCode.Myanmar },
        { "MMR", StaatCode.Myanmar },
        { "MN", StaatCode.Mongolei },
        { "MNE", StaatCode.Montenegro },
        { "MNG", StaatCode.Mongolei },
        { "Moldau", StaatCode.Republik_Moldau },
        { "moldauisch", StaatCode.Republik_Moldau },
        { "Monaco", StaatCode.Monaco },
        { "monegassisch", StaatCode.Monaco },
        { "Mongolei", StaatCode.Mongolei },
        { "mongolisch", StaatCode.Mongolei },
        { "montenegrinisch", StaatCode.Montenegro },
        { "Montenegro", StaatCode.Montenegro },
        { "Mosambik", StaatCode.Mosambik },
        { "mosambikanisch", StaatCode.Mosambik },
        { "MOZ", StaatCode.Mosambik },
        { "MR", StaatCode.Mauretanien },
        { "MRT", StaatCode.Mauretanien },
        { "MT", StaatCode.Malta },
        { "MU", StaatCode.Mauritius },
        { "MUS", StaatCode.Mauritius },
        { "MV", StaatCode.Malediven },
        { "MW", StaatCode.Malawi },
        { "MWI", StaatCode.Malawi },
        { "MX", StaatCode.Mexiko },
        { "MY", StaatCode.Malaysia },
        { "Myanmar", StaatCode.Myanmar },
        { "myanmarisch", StaatCode.Myanmar },
        { "MYS", StaatCode.Malaysia },
        { "MZ", StaatCode.Mosambik },
        { "NA", StaatCode.Namibia },
        { "NAM", StaatCode.Namibia },
        { "Namibia", StaatCode.Namibia },
        { "namibisch", StaatCode.Namibia },
        { "Nauru", StaatCode.Nauru },
        { "nauruisch", StaatCode.Nauru },
        { "NE", StaatCode.Niger },
        { "Nepal", StaatCode.Nepal },
        { "nepalesisch", StaatCode.Nepal },
        { "NER", StaatCode.Niger },
        { "Neuseeland", StaatCode.Neuseeland },
        { "neuseeländisch", StaatCode.Cookinseln },
        { "NG", StaatCode.Nigeria },
        { "NGA", StaatCode.Nigeria },
        { "NI", StaatCode.Nicaragua },
        { "NIC", StaatCode.Nicaragua },
        { "Nicaragua", StaatCode.Nicaragua },
        { "nicaraguanisch", StaatCode.Nicaragua },
        { "Niederlande", StaatCode.Koenigreich_der_Niederlande },
        { "niederländisch", StaatCode.Koenigreich_der_Niederlande },
        { "Niger", StaatCode.Niger },
        { "Nigeria", StaatCode.Nigeria },
        { "nigerianisch", StaatCode.Nigeria },
        { "nigrisch", StaatCode.Niger },
        { "NIU", StaatCode.Niue },
        { "Niue", StaatCode.Niue },
        { "NL", StaatCode.Koenigreich_der_Niederlande },
        { "NLD", StaatCode.Koenigreich_der_Niederlande },
        { "NO", StaatCode.Norwegen },
        { "NOR", StaatCode.Norwegen },
        { "Nordmazedonien", StaatCode.Nordmazedonien },
        { "Norwegen", StaatCode.Norwegen },
        { "norwegisch", StaatCode.Norwegen },
        { "NP", StaatCode.Nepal },
        { "NPL", StaatCode.Nepal },
        { "NR", StaatCode.Nauru },
        { "NRU", StaatCode.Nauru },
        { "NU", StaatCode.Niue },
        { "NZ", StaatCode.Neuseeland },
        { "NZL", StaatCode.Neuseeland },
        { "OM", StaatCode.Oman },
        { "Oman", StaatCode.Oman },
        { "omanisch", StaatCode.Oman },
        { "OMN", StaatCode.Oman },
        { "Österreich", StaatCode.Oesterreich },
        { "österreichisch", StaatCode.Oesterreich },
        { "PA", StaatCode.Panama },
        { "PAK", StaatCode.Pakistan },
        { "Pakistan", StaatCode.Pakistan },
        { "pakistanisch", StaatCode.Pakistan },
        { "Palau", StaatCode.Palau },
        { "palauisch", StaatCode.Palau },
        { "PAN", StaatCode.Panama },
        { "Panama", StaatCode.Panama },
        { "panamaisch", StaatCode.Panama },
        { "Papua-Neuguinea", StaatCode.Papua_Neuguinea },
        { "papua-neuguineisch", StaatCode.Papua_Neuguinea },
        { "Paraguay", StaatCode.Paraguay },
        { "paraguayisch", StaatCode.Paraguay },
        { "PE", StaatCode.Peru },
        { "PER", StaatCode.Peru },
        { "Peru", StaatCode.Peru },
        { "peruanisch", StaatCode.Peru },
        { "PG", StaatCode.Papua_Neuguinea },
        { "PH", StaatCode.Philippinen },
        { "Philippinen", StaatCode.Philippinen },
        { "philippinisch", StaatCode.Philippinen },
        { "PHL", StaatCode.Philippinen },
        { "PK", StaatCode.Pakistan },
        { "PL", StaatCode.Polen },
        { "Plurinationaler Staat Bolivien", StaatCode.Plurinationaler_Staat_Bolivien },
        { "PLW", StaatCode.Palau },
        { "PNG", StaatCode.Papua_Neuguinea },
        { "POL", StaatCode.Polen },
        { "Polen", StaatCode.Polen },
        { "polnisch", StaatCode.Polen },
        { "Portugal", StaatCode.Portugal },
        { "portugiesisch", StaatCode.Portugal },
        { "PRK", StaatCode.Demokratische_Volksrepublik_Korea },
        { "PRT", StaatCode.Portugal },
        { "PRY", StaatCode.Paraguay },
        { "PT", StaatCode.Portugal },
        { "PW", StaatCode.Palau },
        { "PY", StaatCode.Paraguay },
        { "QA", StaatCode.Katar },
        { "QAT", StaatCode.Katar },
        { "Republik Korea", StaatCode.Republik_Korea },
        { "Republik Moldau", StaatCode.Republik_Moldau },
        { "RO", StaatCode.Rumaenien },
        { "ROU", StaatCode.Rumaenien },
        { "RS", StaatCode.Serbien },
        { "RU", StaatCode.Russische_Foederation },
        { "Ruanda", StaatCode.Ruanda },
        { "ruandisch", StaatCode.Ruanda },
        { "Rumänien", StaatCode.Rumaenien },
        { "rumänisch", StaatCode.Rumaenien },
        { "RUS", StaatCode.Russische_Foederation },
        { "russisch", StaatCode.Russische_Foederation },
        { "Russische Föderation", StaatCode.Russische_Foederation },
        { "RW", StaatCode.Ruanda },
        { "RWA", StaatCode.Ruanda },
        { "SA", StaatCode.Saudi_Arabien },
        { "Salomonen", StaatCode.Salomonen },
        { "salomonisch", StaatCode.Salomonen },
        { "salvadorianisch", StaatCode.El_Salvador },
        { "Sambia", StaatCode.Sambia },
        { "sambisch", StaatCode.Sambia },
        { "Samoa", StaatCode.Samoa },
        { "samoanisch", StaatCode.Samoa },
        { "San Marino", StaatCode.San_Marino },
        { "san-marinesisch", StaatCode.San_Marino },
        { "São Tomé und Príncipe", StaatCode.S_o_Tom_und_Pr_ncipe },
        { "são-toméisch", StaatCode.S_o_Tom_und_Pr_ncipe },
        { "SAU", StaatCode.Saudi_Arabien },
        { "Saudi-Arabien", StaatCode.Saudi_Arabien },
        { "saudi-arabisch", StaatCode.Saudi_Arabien },
        { "SB", StaatCode.Salomonen },
        { "SC", StaatCode.Seychellen },
        { "Schweden", StaatCode.Schweden },
        { "schwedisch", StaatCode.Schweden },
        { "Schweiz", StaatCode.Schweiz },
        { "schweizerisch", StaatCode.Schweiz },
        { "SD", StaatCode.Sudan },
        { "SDN", StaatCode.Sudan },
        { "SE", StaatCode.Schweden },
        { "SEN", StaatCode.Senegal },
        { "Senegal", StaatCode.Senegal },
        { "senegalesisch", StaatCode.Senegal },
        { "Serbien", StaatCode.Serbien },
        { "serbisch", StaatCode.Serbien },
        { "Seychellen", StaatCode.Seychellen },
        { "seychellisch", StaatCode.Seychellen },
        { "SG", StaatCode.Singapur },
        { "SGP", StaatCode.Singapur },
        { "SI", StaatCode.Slowenien },
        { "Sierra Leone", StaatCode.Sierra_Leone },
        { "sierra-leonisch", StaatCode.Sierra_Leone },
        { "Simbabwe", StaatCode.Simbabwe },
        { "simbabwisch", StaatCode.Simbabwe },
        { "Singapur", StaatCode.Singapur },
        { "singapurisch", StaatCode.Singapur },
        { "SK", StaatCode.Slowakei },
        { "SL", StaatCode.Sierra_Leone },
        { "SLB", StaatCode.Salomonen },
        { "SLE", StaatCode.Sierra_Leone },
        { "Slowakei", StaatCode.Slowakei },
        { "slowakisch", StaatCode.Slowakei },
        { "Slowenien", StaatCode.Slowenien },
        { "slowenisch", StaatCode.Slowenien },
        { "SLV", StaatCode.El_Salvador },
        { "SM", StaatCode.San_Marino },
        { "SMR", StaatCode.San_Marino },
        { "SN", StaatCode.Senegal },
        { "SO", StaatCode.Somalia },
        { "SOM", StaatCode.Somalia },
        { "Somalia", StaatCode.Somalia },
        { "somalisch", StaatCode.Somalia },
        { "Spanien", StaatCode.Spanien },
        { "spanisch", StaatCode.Spanien },
        { "SR", StaatCode.Suriname },
        { "SRB", StaatCode.Serbien },
        { "Sri Lanka", StaatCode.Sri_Lanka },
        { "sri-lankisch", StaatCode.Sri_Lanka },
        { "SS", StaatCode.Suedsudan },
        { "SSD", StaatCode.Suedsudan },
        { "ST", StaatCode.S_o_Tom_und_Pr_ncipe },
        { "St. Kitts und Nevis", StaatCode.St_Kitts_und_Nevis },
        { "St. Lucia", StaatCode.St_Lucia },
        { "St. Vincent und die Grenadinen", StaatCode.St_Vincent_und_die_Grenadinen },
        { "STP", StaatCode.S_o_Tom_und_Pr_ncipe },
        { "Südafrika", StaatCode.Suedafrika },
        { "südafrikanisch", StaatCode.Suedafrika },
        { "Sudan", StaatCode.Sudan },
        { "sudanesisch", StaatCode.Sudan },
        { "Südsudan", StaatCode.Suedsudan },
        { "südsudanesisch", StaatCode.Suedsudan },
        { "SUR", StaatCode.Suriname },
        { "Suriname", StaatCode.Suriname },
        { "surinamisch", StaatCode.Suriname },
        { "SV", StaatCode.El_Salvador },
        { "SVK", StaatCode.Slowakei },
        { "SVN", StaatCode.Slowenien },
        { "SWE", StaatCode.Schweden },
        { "SWZ", StaatCode.Eswatini },
        { "SY", StaatCode.Arabische_Republik_Syrien },
        { "SYC", StaatCode.Seychellen },
        { "SYR", StaatCode.Arabische_Republik_Syrien },
        { "Syrien", StaatCode.Arabische_Republik_Syrien },
        { "syrisch", StaatCode.Arabische_Republik_Syrien },
        { "SZ", StaatCode.Eswatini },
        { "tadschikisch", StaatCode.Tadschikistan },
        { "Tadschikistan", StaatCode.Tadschikistan },
        { "Tansania", StaatCode.Vereinigte_Republik_Tansania },
        { "tansanisch", StaatCode.Vereinigte_Republik_Tansania },
        { "TCD", StaatCode.Tschad },
        { "TD", StaatCode.Tschad },
        { "TG", StaatCode.Togo },
        { "TGO", StaatCode.Togo },
        { "TH", StaatCode.Thailand },
        { "THA", StaatCode.Thailand },
        { "Thailand", StaatCode.Thailand },
        { "thailändisch", StaatCode.Thailand },
        { "Timor-Leste", StaatCode.Timor_Leste },
        { "TJ", StaatCode.Tadschikistan },
        { "TJK", StaatCode.Tadschikistan },
        { "TKM", StaatCode.Turkmenistan },
        { "TL", StaatCode.Timor_Leste },
        { "TLS", StaatCode.Timor_Leste },
        { "TM", StaatCode.Turkmenistan },
        { "TN", StaatCode.Tunesien },
        { "TO", StaatCode.Tonga },
        { "Togo", StaatCode.Togo },
        { "togoisch", StaatCode.Togo },
        { "TON", StaatCode.Tonga },
        { "Tonga", StaatCode.Tonga },
        { "tongaisch", StaatCode.Tonga },
        { "TR", StaatCode.Tuerkei },
        { "Trinidad und Tobago", StaatCode.Trinidad_und_Tobago },
        { "Tschad", StaatCode.Tschad },
        { "tschadisch", StaatCode.Tschad },
        { "Tschechien", StaatCode.Tschechien },
        { "tschechisch", StaatCode.Tschechien },
        { "TT", StaatCode.Trinidad_und_Tobago },
        { "TTO", StaatCode.Trinidad_und_Tobago },
        { "TUN", StaatCode.Tunesien },
        { "Tunesien", StaatCode.Tunesien },
        { "tunesisch", StaatCode.Tunesien },
        { "TUR", StaatCode.Tuerkei },
        { "Türkei", StaatCode.Tuerkei },
        { "türkisch", StaatCode.Tuerkei },
        { "turkmenisch", StaatCode.Turkmenistan },
        { "Turkmenistan", StaatCode.Turkmenistan },
        { "TUV", StaatCode.Tuvalu },
        { "Tuvalu", StaatCode.Tuvalu },
        { "tuvaluisch", StaatCode.Tuvalu },
        { "TV", StaatCode.Tuvalu },
        { "TZ", StaatCode.Vereinigte_Republik_Tansania },
        { "TZA", StaatCode.Vereinigte_Republik_Tansania },
        { "UA", StaatCode.Ukraine },
        { "UG", StaatCode.Uganda },
        { "UGA", StaatCode.Uganda },
        { "Uganda", StaatCode.Uganda },
        { "ugandisch", StaatCode.Uganda },
        { "UKR", StaatCode.Ukraine },
        { "Ukraine", StaatCode.Ukraine },
        { "ukrainisch", StaatCode.Ukraine },
        { "ungarisch", StaatCode.Ungarn },
        { "Ungarn", StaatCode.Ungarn },
        { "Uruguay", StaatCode.Uruguay },
        { "uruguayisch", StaatCode.Uruguay },
        { "URY", StaatCode.Uruguay },
        { "US", StaatCode.Vereinigte_Staaten },
        { "USA", StaatCode.Vereinigte_Staaten },
        { "usbekisch", StaatCode.Usbekistan },
        { "Usbekistan", StaatCode.Usbekistan },
        { "UY", StaatCode.Uruguay },
        { "UZ", StaatCode.Usbekistan },
        { "UZB", StaatCode.Usbekistan },
        { "VA", StaatCode.Vatikanstadt },
        { "Vanuatu", StaatCode.Vanuatu },
        { "vanuatuisch", StaatCode.Vanuatu },
        { "VAT", StaatCode.Vatikanstadt },
        { "vatikanisch", StaatCode.Vatikanstadt },
        { "Vatikanstadt", StaatCode.Vatikanstadt },
        { "VC", StaatCode.St_Vincent_und_die_Grenadinen },
        { "VCT", StaatCode.St_Vincent_und_die_Grenadinen },
        { "VE", StaatCode.Bolivarische_Republik_Venezuela },
        { "VEN", StaatCode.Bolivarische_Republik_Venezuela },
        { "venezolanisch", StaatCode.Bolivarische_Republik_Venezuela },
        { "Venezuela", StaatCode.Bolivarische_Republik_Venezuela },
        { "Vereinigte Arabische Emirate", StaatCode.Vereinigte_Arabische_Emirate },
        { "Vereinigte Republik Tansania", StaatCode.Vereinigte_Republik_Tansania },
        { "Vereinigte Staaten", StaatCode.Vereinigte_Staaten },
        { "Vereinigtes Königreich", StaatCode.Vereinigtes_Koenigreich },
        { "Vietnam", StaatCode.Vietnam },
        { "vietnamesisch", StaatCode.Vietnam },
        { "vincentisch", StaatCode.St_Vincent_und_die_Grenadinen },
        { "VN", StaatCode.Vietnam },
        { "VNM", StaatCode.Vietnam },
        { "von St. Kitts und Nevis", StaatCode.St_Kitts_und_Nevis },
        { "von Timor-Leste", StaatCode.Timor_Leste },
        { "von Trinidad und Tobago", StaatCode.Trinidad_und_Tobago },
        { "VU", StaatCode.Vanuatu },
        { "VUT", StaatCode.Vanuatu },
        { "WS", StaatCode.Samoa },
        { "WSM", StaatCode.Samoa },
        { "XK", StaatCode.Kosovo },
        { "XXK", StaatCode.Kosovo },
        { "YE", StaatCode.Jemen },
        { "YEM", StaatCode.Jemen },
        { "ZA", StaatCode.Suedafrika },
        { "ZAF", StaatCode.Suedafrika },
        { "zentralafrikanisch", StaatCode.Zentralafrikanische_Republik },
        { "Zentralafrikanische Republik", StaatCode.Zentralafrikanische_Republik },
        { "ZM", StaatCode.Sambia },
        { "ZMB", StaatCode.Sambia },
        { "ZW", StaatCode.Simbabwe },
        { "ZWE", StaatCode.Simbabwe },
        { "Zypern", StaatCode.Zypern },
        { "zyprisch", StaatCode.Zypern },
    };

    /// <summary>
    /// Tries to parse a string value (Code, Name, ISO, etc.) into a StaatCode.
    /// </summary>
    public static bool TryParse(string value, out StaatCode code)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
             code = default;
             return false;
        }

        return Map.TryGetValue(value.Trim(), out code);
    }
}
